### ISSUE TITLE
Suggestions to avoid duplicate deduction for phase two

### ISSUE THREAD

**Issue by tianhanl** [HAOYU-LI/csci499_haoyuli#20]
Missing parameter validation

https://github.com/HAOYU-LI/csci499_haoyuli/blob/0ae064670cc1ebeecbca71d20797471db0192756/warble/warble_service_impl.cc#L61
> -3, reply with invalid ID should fail

https://github.com/HAOYU-LI/csci499_haoyuli/blob/0ae064670cc1ebeecbca71d20797471db0192756/warble/warble_service_impl.cc#L91

> -1, users should not be able to follow themselves

**Comment by HAOYU-LI** [comment]
Solved. Close this issue.
